spring:
  data:
    mongodb:
#      uri: mongodb://admin:ertale@ms_mongodb:27017/customer?authSource=admin
      username: admin
      password: ertale
      host: localhost
      port: 27017
      database: customer
      authentication-database: admin

server:
  port: 8020