spring:
  data:
    mongodb:
      username: admin
      password: ertale
      host: localhost
      port: 27017
      database: notification
      authentication-database: admin
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: paymentGroup,orderGroup
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: '*'
        spring.json.type.mapping: orderConfirmation:com.zcommerce.ecommerce.notification.kafka.order.OrderConfirmation,paymentConfirmation:com.zcommerce.ecommerce.notification.kafka.payment.PaymentConfirmation
        spring.json.value.default.type: com.zcommerce.ecommerce.notification.kafka.order.OrderConfirmation


  mail:
    host: localhost
    port: 1025
    username: admin
    password: ertale
    properties:
      mail:
        smtp:
          trust: "*"
        auth: true
        starttls:
          enabled: true
        connectiontimeout: 5000
        timeout: 3000
        writetiemout: 5000
server:
  port: 8060
